Feature/get users by project
WildCodeSchool/2109-wns-remote3-taskberry-back pull request #12
Opened 2022-02-24 15:11 UTC by Guy-deMessimy

2022-02-24 15:14 UTC, Guy-deMessimy commented
https://fil-rouge-project.atlassian.net/jira/software/projects/FRP/boards/1?selectedIssue=FRP-82

2022-02-25 08:59 UTC, brdtheo requested changes

2022-02-25 08:59 UTC, brdtheo commented on src/repositories/projectsRepository.ts
> +      return null;
```ts
throw new Error("Project does not exist");
```

2022-02-25 09:25 UTC, brdtheo approved these changes

2022-02-25 09:25 UTC, merged